from setuptools import setup, find_packages

setup(
    name="fastyr_ai_pipeline",
    version="0.1.0",
    author="William Jefferson Mensah",
    author_email="mensahjefferson69@gmail.com",
    description="A flexible AI pipeline for STT, LLM, and TTS",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/cuuj69/fastyr",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "requests",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "sqlalchemy>=1.4.0",
        "alembic>=1.7.0",
        "strawberry-graphql>=0.96.0",
        "sentry-sdk>=1.5.0",
        "structlog>=21.1.0",
        "dependency-injector>=4.39.1",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "python-multipart>=0.0.5",
        "asyncpg>=0.25.0",
        "prometheus-client>=0.12.0",
        "python-jose[cryptography]>=3.3.0",
        "uvicorn[standard]>=0.15.0",
        "gunicorn>=20.1.0",
        "psycopg2-binary>=2.9.1",
        "asyncpg>=0.25.0",
        "sqlalchemy[asyncio]>=1.4.0",
        "aiosqlite>=0.17.0",
        "aiofiles>=23.2.1",
        "PyJWT>=2.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-mock>=3.10.0",
            "coverage>=7.2.0",
            "httpx>=0.24.0",
            "aiohttp>=3.8.0",
            "pytest-env>=1.0.0",
        ]
    },
    python_requires=">=3.7",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating Systems :: OS Independent",
    ],
)
