apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastyr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastyr
  template:
    metadata:
      labels:
        app: fastyr
    spec:
      containers:
      - name: fastyr
        image: fastyr:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fastyr-secrets
              key: database-url 